#!/usr/bin/env bash


# install all the dependencies and pack everything into one file domjs_bundle.js (converted to es2015).
npm install jsdom babel-core babel-cli babel-preset-es2015 browserify babel-polyfill

browserify domjs.js -o domjs_bundle.js -t [ babelify --presets [ es2015 ] ] -g [ babelify --presets [ es2015 ] ]

# translate domjs_bundle.js using js2py -> generates jsdom.py
echo "Generating jsdom.py... This can take ages and ages"
python -c "import sys;sys.setrecursionlimit(100000);import js2py;js2py.translate_file('domjs_bundle.js', 'jsdom.py');"
rm domjs_bundle.js
echo "Done!"
